[package]
name = "pessoa"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", default-features = false, features = [
    "std",
    "derive",
] }
fake_rs = { package = "fake", version = "4.0", default-features = false }
