[package]
name = "pessoa"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", default-features = false, features = [
    "std",
    "derive",
] }
fakeit = { version = "1.3", default-features = false }
