name: Main Workflow
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo fmt --all --check -- --config imports_granularity=Crate,group_imports=One
      - run: cargo clippy --all --all-features -- -D warnings
      - run: cargo test
      - run: cargo install cargo-sort && cargo sort --check
