name: Publish Lib workflow
on:
  push:
    tags: '*'
    paths: "pessoa"
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: cargo publish
        working-directory: pessoa
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
